global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'docker-agent-flask'
    static_configs:
      - targets: ['flask-app:8001']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'docker-agent-rag-api'
    static_configs:
      - targets: ['rag-api:8000']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']